name: Play Store Auto Reply

on:
  workflow_dispatch:
    inputs:
      days_back:
        description: '🔍 追溯过去多少天内的评论？'
        required: true
        default: '7'
        type: string

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install google-api-python-client google-auth requests

      - name: Run Main Script
        env:
          GP_JSON_KEY: ${{ secrets.GP_JSON_KEY }}
          AI_REPLY_KEY: ${{ secrets.AI_REPLY_KEY }}
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        # 核心：将前端输入的天数传给 Python
        run: python main.py ${{ github.event.inputs.days_back }}
